set(USER_ANALYZERS $$USERANA$$)

set(TARGET_EXEC $$TARGET$$)
set(ANA_LIBS $$USERANA$$ $$FWANA$$ $$EXAMPLEANA$$)

set(EXTRA_LIBS "$$EXTRALIBS$$")
set(EXTRA_LIBS_DIRS "$$EXTRALIBSDIRS$$")
set(EXTRA_INCLUDE_DIRS "$$EXTRAINCLUDEDIRS$$")