setenv ANALYSISFW_PATH $$ANALYSISFW$$
setenv ANALYSISFW_USERDIR $$USERDIR$$
setenv NA62MCSOURCE $$NA62MCSOURCE$$

if ( "$LD_LIBRARY_PATH" !~ "*$ANALYSISFW_PATH/lib*" ) then
	setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${ANALYSISFW_PATH}/lib
	setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${ANALYSISFW_USERDIR}/lib
	setenv PATH ${PATH}:${ANALYSISFW_PATH}
endif

source $ANALYSISFW_PATH/scripts/env.csh
